# Generated by Django 4.1.7 on 2023-07-26 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servidores',
            fields=[
                ('status', models.CharField(default='ativo', max_length=10)),
                ('name', models.CharField(max_length=45)),
                ('mat', models.IntegerField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('genere', models.CharField(max_length=1)),
                ('personal_cell', models.CharField(max_length=11)),
                ('work_cell', models.CharField(max_length=11)),
                ('office', models.CharField(max_length=20)),
                ('entrata', models.TimeField()),
                ('saida', models.TimeField()),
                ('admissao', models.DateField(null=True)),
                ('gp', models.CharField(blank=True, max_length=10, null=True)),
                ('cpf', models.IntegerField()),
                ('cnh', models.IntegerField()),
                ('cat_cnh', models.CharField(max_length=2, null=True)),
                ('district', models.CharField(max_length=30, null=True)),
                ('city', models.CharField(max_length=30, null=True)),
            ],
        ),
    ]
