# Generated by Django 4.1.7 on 2023-07-26 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sefit', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servidores',
            old_name='admissao',
            new_name='admission',
        ),
        migrations.RenameField(
            model_name='servidores',
            old_name='entrata',
            new_name='begin_hour',
        ),
        migrations.RenameField(
            model_name='servidores',
            old_name='saida',
            new_name='exit_hour',
        ),
    ]
