# Generated by Django 4.1.7 on 2023-07-30 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sefit', '0002_rename_admissao_servidores_admission_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DayOff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mat', models.IntegerField()),
                ('dayOff', models.CharField(max_length=20)),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
            ],
        ),
    ]
