# Generated by Django 4.2.7 on 2023-12-26 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sefit', '0003_alter_schedulerworker_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduler',
            name='id',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
