# Generated by Django 4.1.7 on 2023-07-30 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sefit', '0003_dayoff'),
    ]

    operations = [
        migrations.AddField(
            model_name='dayoff',
            name='comment',
            field=models.TextField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
