# Generated by Django 4.1.7 on 2023-07-30 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sefit', '0004_dayoff_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dayoff',
            name='comment',
            field=models.TextField(max_length=150, null=True),
        ),
    ]
