# Generated by Django 4.1.7 on 2023-07-30 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sefit', '0005_alter_dayoff_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dayoff',
            name='mat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sefit.servidores'),
        ),
    ]
