# Generated by Django 4.1.7 on 2023-07-30 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sefit', '0006_alter_dayoff_mat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dayoff',
            old_name='mat',
            new_name='worker',
        ),
    ]
