# Generated by Django 4.1.7 on 2023-07-30 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sefit', '0007_rename_mat_dayoff_worker'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dayoff',
            old_name='worker',
            new_name='mat',
        ),
    ]
