# Generated by Django 4.2.7 on 2023-11-19 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sefit', '0008_rename_worker_dayoff_mat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scheduler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=20)),
                ('eqp', models.CharField(max_length=20)),
                ('func', models.CharField(max_length=20)),
                ('local', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('timeFinish', models.TimeField(null=True)),
                ('timeStart', models.TimeField(null=True)),
            ],
        ),
    ]
