# Generated by Django 4.2.7 on 2023-11-19 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sefit', '0009_scheduler'),
    ]

    operations = [
        migrations.CreateModel(
            name='Local',
            fields=[
                ('roteiro_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('local', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='scheduler',
            name='func',
            field=models.CharField(choices=[('agt', 'AGENTE'), ('coo', 'COORDENADOR'), ('sup', 'SUPERVISOR')], max_length=3),
        ),
        migrations.AlterField(
            model_name='scheduler',
            name='local',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sefit.local'),
        ),
    ]
