# Generated by Django 4.2.7 on 2023-12-27 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sefit', '0009_alter_schedulerworker_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedulerworker',
            name='eqp',
            field=models.CharField(choices=[('vtr', 'VIATURA'), ('mt', 'MOTO'), ('po', 'A Pé'), ('oth', 'Other')], max_length=4),
        ),
        migrations.AlterField(
            model_name='schedulerworker',
            name='func',
            field=models.CharField(choices=[('agt', 'AGENTE'), ('sup', 'SUPERVISOR'), ('coo', 'COORDENADOR'), ('ger', 'Gerente')], max_length=3),
        ),
    ]
