# Generated by Django 4.2.7 on 2023-11-19 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sefit', '0010_local_alter_scheduler_func_alter_scheduler_local'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduler',
            name='event_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='scheduler',
            name='eqp',
            field=models.CharField(choices=[('vtr', 'VIATURA'), ('mt', 'MOTO'), ('po', 'A Pé')], max_length=4),
        ),
    ]
