# Generated by Django 4.2.7 on 2023-12-27 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sefit', '0010_alter_schedulerworker_eqp_alter_schedulerworker_func'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='scheduler',
            unique_together={('date', 'typeScheduler', 'obs')},
        ),
    ]
