# Generated by Django 4.2.7 on 2023-11-19 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sefit', '0011_scheduler_event_date_alter_scheduler_eqp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduler',
            name='name',
            field=models.CharField(max_length=40),
        ),
    ]
